main: ca.fredelin.grisesiarpg_combat.main
name: GrisesiaRpg_Combat
version: 0.0.1
author: [Crusader, fredelin]
api-version: '1.17'
description: Un simple cooldown de combat.
depend: [WorldEdit, WorldGuard,WorldGuardEvents]
softdepend: [Multiverse-Core, Multiverse-Portals]